<?php

namespace Arnm\WidgetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WidgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WidgetRepository extends EntityRepository
{

    public function findAllByPageId($pageId)
    {
        $qBuilder = $this->createQueryBuilder('w');
        $qBuilder->addSelect('p');
        $qBuilder->leftJoin('w.params', 'p');
        $qBuilder->where('w.pageId = :pageId')->setParameter('pageId', $pageId);
        $qBuilder->orderBy('w.sequence', 'ASC');

        return $qBuilder->getQuery()->getResult();
    }
}